language: ruby
before_script: 'bundle exec rake test:setup'
script: 'bundle exec rake test:all'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
before_install:
  - gem install bundler -v 1.11.2
